export const PATIENTS_SEARCH = "PATIENT_SEARCH";
export const PATIENTS_LOADING = "PATIENTS_LOADING";
export const PATIENTS_SEARCH_SUCCESS = "PATIENTS_SEARCH_SUCCESS";
export const PATIENTS_SEARCH_FAILED = "PATIENTS_SEARCH_FAILED";
export const PATIENTS_LOADED ="PATIENTS_LOADED"